"""First Migration

Revision ID: 0c9541ad6499
Revises: 
Create Date: 2022-08-15 00:03:31.179244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9541ad6499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long', sa.Text(), nullable=True),
    sa.Column('short', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_table')
    # ### end Alembic commands ###
